### ISSUE TITLE
Рації Моторола - діагностика підключення

### ISSUE THREAD

**Issue by OleksandrS22** [Syopic/onlinebattlecity#30]

**Comment by OleksandrS22** [comment]
Програма CPS пише лог в C:\ProgramData\Motorola\CommonCPS\Motorola Device Communication\CPSShell_CommonCommunication.log

**Comment by OleksandrS22** [comment]
Проблемний кусок при підключенні рації в цьому лозі нижче. Якщо коротко - він не може встановити з"єднання за адресою 192.168.10.1:8002 (порт 8002), тому що рація відмовляє.
[04/12/22 10:14:10.731],[25],VERBOSE,"TCP OpenPort: 192.168.10.1:8002",   at Motorola.Common.Communication.CommunicationPipe.TcpClientCommPipe.OpenPort(Int32 timeout)
CommonCommunicationError.CommonCommunicationException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.10.1:8002 ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.10.1:8002
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Motorola.Common.Communication.CommunicationPipe.TcpClientCommPipe.OpenPort(Int32 timeout)
   --- End of inner exception stack trace ---
   at Motorola.Common.Communication.CommunicationPipe.TcpClientCommPipe.OpenPort(Int32 timeout)
   at Motorola.Common.Communication.ab.an(ICommunicationPipe A_0)
   at Motorola.Common.Communication.Xnl.Connect(ICommunicationPipe communicationPipe)
   at Motorola.Common.Communication.CommunicationPipe.NLCommPipe.OpenPort(Int32 timeout)
[04/12/22 10:14:12.805],[25],VERBOSE,"TCP ClosePort!",   at Motorola.Common.Communication.CommunicationPipe.TcpCommPipe.ClosePort()
[04/12/22 10:14:12.812],[25],VERBOSE,"TCP OpenPort: 192.168.10.1:8002",   at Motorola.Common.Communication.CommunicationPipe.TcpClientCommPipe.OpenPort(Int32 timeout)
